# Generated by Django 2.1.3 on 2018-12-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depoimentos',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='descricao1',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='descricao2',
        ),
        migrations.AlterField(
            model_name='servicos',
            name='imagem',
            field=models.ImageField(upload_to='servicos/imagens', verbose_name='Imagem'),
        ),
    ]
