# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20181213_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='titulo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
