# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-15 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_portfolio_imagemslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimentos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='depoimentos/imagens', verbose_name='Imagem'),
        ),
    ]
