# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-16 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20181215_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['titulo'], 'verbose_name': 'Servicos', 'verbose_name_plural': 'Servicos'},
        ),
    ]
