# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20190103_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimentos',
            name='atalho',
            field=models.SlugField(default='test', verbose_name='Atalho'),
        ),
    ]
