# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-28 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20190103_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inicio',
        ),
        migrations.RemoveField(
            model_name='parceiros',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='imagemslide',
        ),
        migrations.RemoveField(
            model_name='quemsomos',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='quemsomos',
            name='titulo',
        ),
    ]
